smtp = 'smtp.gmail.com'
username= 'username@gmail.com'
password= 'password'
from_email = 'from@gmail.com'
production_to_email = 'prodto@gmail.com'
server_url = 'http://localhost:5051'
maintainance_to_email = 'maintto@gmail.com'
