smtp = 'smtp.gmail.com'
username= 'manuquickmail@gmail.com'
password= 'wojynkuigxyiqaxl'
from_email = 'manuquickmail@gmail.com'
production_to_email = 'manmathayya.m@dtcinfotech.com'
server_url = 'http://localhost:5051'
maintainance_to_email = 'manmathayya.m@dtcinfotech.com'
