smtp = "smtp.office365.com"
# smtp = 'smtp.gmail.com'
# username= 'manuquickmail@gmail.com'
# password= 'wojynkuigxyiqaxl'
# from_email = 'manuquickmail@gmail.com'
username= "pankaj.jogi@tiei.toyota-industries.com"
password= "WB4psCxK"
from_email = "pankaj.jogi@tiei.toyota-industries.com"
server_url = 'http://10.82.126.73:5051'
production_to_email =  "yousuf@tiei.toyota-industries.com, benjamindavid.s@tiei.toyota-industries.com"
maintainance_to_email =  "yousuf@tiei.toyota-industries.com, benjamindavid.s@tiei.toyota-industries.com"
# production_to_email =  "yousuf@tiei.toyota-industries.com"
# maintainance_to_email =  "yousuf@tiei.toyota-industries.com"
